APP_TITLE = "Universal PDF Converter"
APP_DIMENSIONS = "700x500"
THEME_MODE = "Dark"
THEME_COLOR = "blue"
BUTTON_COLOR = "#28a745"
HOVER_COLOR = "#218838"

PDF_FONT = "Helvetica"
PDF_FONT_SIZE = 12
PDF_MARGIN_LEFT = 72
PDF_MARGIN_BOTTOM = 72
PDF_LINE_HEIGHT = 15